In [ ]:
# data cleaning and exploratory data analysis
import pandas as pd
data=pd.read_excel("/content/employee.xlsx")
data

,Employee_ID,Name,Age,Gender,Department,Salary,City,Joining_Dates
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,NaN,F,HR,38000,Chennai,2022-02-15
2,E103,John,28.0,Male,Finance,55000,NaN,2023-05-10
3,NaN,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,NaN,Female,HR,-38000,Chennai,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,NaN,IT,47000,Delhi,2023-02-01
8,E109,NaN,-27.0,Female,Finance,52000,Hyderabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chennai,2024-01-05

In [ ]:
data.isnull()

   Employee_ID   Name    Age  Gender  Department  Salary   City  Joining_Dates
0        False  False  False   False       False   False  False          False
1        False  False   True   False       False   False  False          False
2        False  False  False   False       False   False   True          False
3         True  False  False   False       False   False  False          False
4        False  False  False   False       False   False  False          False
5        False  False   True   False       False   False  False          False
6        False  False  False   False       False   False  False          False
7        False  False  False    True       False   False  False          False
8        False   True  False   False       False   False  False          False
9        False  False  False   False       False   False  False          False

In [ ]:
data.isnull().sum()

Employee_ID      1
Name             1
Age              2
Gender           1
Department       0
Salary           0
City             1
Joining_Dates    0
dtype: int64

In [ ]:
data.isnull().sum().sum()

np.int64(6)

In [ ]:
data['City']=data['City'].fillna('Mangaluru')
data

,Employee_ID,Name,Age,Gender,Department,Salary,City,Joining_Dates
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,NaN,F,HR,38000,Chennai,2022-02-15
2,E103,John,28.0,Male,Finance,55000,Mangaluru,2023-05-10
3,NaN,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,NaN,Female,HR,-38000,Chennai,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,NaN,IT,47000,Delhi,2023-02-01
8,E109,NaN,-27.0,Female,Finance,52000,Hyderabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chennai,2024-01-05

In [ ]:
data['Age']=data['Age'].fillna(20)
data

,Employee_ID,Name,Age,Gender,Department,Salary,City,Joining_Dates
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,20.0,F,HR,38000,Chennai,2022-02-15
2,E103,John,28.0,Male,Finance,55000,Mangaluru,2023-05-10
3,NaN,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,20.0,Female,HR,-38000,Chennai,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,NaN,IT,47000,Delhi,2023-02-01
8,E109,NaN,-27.0,Female,Finance,52000,Hyderabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chennai,2024-01-05

In [ ]:
data['Employee_ID']=data['Employee_ID'].fillna(data["Employee_ID"].mode()[0])
data

,Employee_ID,Name,Age,Gender,Department,Salary,City,Joining_Dates
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,20.0,F,HR,38000,Chennai,2022-02-15
2,E103,John,28.0,Male,Finance,55000,Mangaluru,2023-05-10
3,E101,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,20.0,Female,HR,-38000,Chennai,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,NaN,IT,47000,Delhi,2023-02-01
8,E109,NaN,-27.0,Female,Finance,52000,Hyderabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chennai,2024-01-05

In [ ]:
data.isnull().sum()

Employee_ID      0
Name             1
Age              0
Gender           1
Department       0
Salary           0
City             0
Joining_Dates    0
dtype: int64

In [ ]:
data['Gender']=data['Gender'].fillna('Female')
data

,Employee_ID,Name,Age,Gender,Department,Salary,City,Joining_Dates
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,20.0,F,HR,38000,Chennai,2022-02-15
2,E103,John,28.0,Male,Finance,55000,Mangaluru,2023-05-10
3,E101,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,20.0,Female,HR,-38000,Chennai,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,Female,IT,47000,Delhi,2023-02-01
8,E109,NaN,-27.0,Female,Finance,52000,Hyderabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chennai,2024-01-05

In [ ]:
data.isnull().sum()

Employee_ID      0
Name             1
Age              0
Gender           0
Department       0
Salary           0
City             0
Joining_Dates    0
dtype: int64

In [ ]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [ ]:
data.duplicated().sum()

np.int64(0)

In [ ]:
import pandas as pd
data=pd.read_excel("/content/employee.xlsx")
data

,Employee_ID,Name,Age,Gender,Department,Salary,City,Joining_Dates
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,NaN,F,HR,38000,Chennai,2022-02-15
2,E103,John,28.0,Male,Finance,55000,NaN,2023-05-10
3,NaN,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,NaN,Female,HR,-38000,Chennai,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,NaN,IT,47000,Delhi,2023-02-01
8,E109,NaN,-27.0,Female,Finance,52000,Hyderabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chennai,2024-01-05

In [ ]:
df=data.drop('Joining_Dates',axis=1)
df

  Employee_ID      Name    Age  Gender Department  Salary       City
0        E101     Akash   25.0       M         IT   45000  Bengaluru
1        E102     Megha    NaN       F         HR   38000    Chennai
2        E103      John   28.0    Male    Finance   55000        NaN
3         NaN     Kavya  240.0  Female         IT   48000     Mysuru
4        E105    Darshi   26.0    Male      Sales   25000  Bengaluru
5        E106   Supriya    NaN  Female         HR  -38000    Chennai
6        E107    Darshi   26.0    Male      Sales   25000  Bengaluru
7        E108     Sneha   23.0     NaN         IT   47000      Delhi
8        E109       NaN  -27.0  Female    Finance   52000  Hyderabad
9        E110     Vikas   22.0    Male         IT   99999    Chennai

In [ ]:
import numpy as np
df.loc[df['Age']>90,'Age']=np.nan
df

  Employee_ID      Name   Age  Gender Department  Salary       City
0        E101     Akash  25.0       M         IT   45000  Bengaluru
1        E102     Megha   NaN       F         HR   38000    Chennai
2        E103      John  28.0    Male    Finance   55000        NaN
3         NaN     Kavya   NaN  Female         IT   48000     Mysuru
4        E105    Darshi  26.0    Male      Sales   25000  Bengaluru
5        E106   Supriya   NaN  Female         HR  -38000    Chennai
6        E107    Darshi  26.0    Male      Sales   25000  Bengaluru
7        E108     Sneha  23.0     NaN         IT   47000      Delhi
8        E109       NaN -27.0  Female    Finance   52000  Hyderabad
9        E110     Vikas  22.0    Male         IT   99999    Chennai

In [ ]:
df.loc[df['Age']<0,'Age']=np.nan
df

  Employee_ID      Name   Age  Gender Department  Salary       City
0        E101     Akash  25.0       M         IT   45000  Bengaluru
1        E102     Megha   NaN       F         HR   38000    Chennai
2        E103      John  28.0    Male    Finance   55000        NaN
3         NaN     Kavya   NaN  Female         IT   48000     Mysuru
4        E105    Darshi  26.0    Male      Sales   25000  Bengaluru
5        E106   Supriya   NaN  Female         HR  -38000    Chennai
6        E107    Darshi  26.0    Male      Sales   25000  Bengaluru
7        E108     Sneha  23.0     NaN         IT   47000      Delhi
8        E109       NaN   NaN  Female    Finance   52000  Hyderabad
9        E110     Vikas  22.0    Male         IT   99999    Chennai

In [ ]:
df['Age']=df['Age'].fillna(df['Age'].mean())
df

  Employee_ID      Name   Age  Gender Department  Salary       City
0        E101     Akash  25.0       M         IT   45000  Bengaluru
1        E102     Megha  25.0       F         HR   38000    Chennai
2        E103      John  28.0    Male    Finance   55000        NaN
3         NaN     Kavya  25.0  Female         IT   48000     Mysuru
4        E105    Darshi  26.0    Male      Sales   25000  Bengaluru
5        E106   Supriya  25.0  Female         HR  -38000    Chennai
6        E107    Darshi  26.0    Male      Sales   25000  Bengaluru
7        E108     Sneha  23.0     NaN         IT   47000      Delhi
8        E109       NaN  25.0  Female    Finance   52000  Hyderabad
9        E110     Vikas  22.0    Male         IT   99999    Chennai

In [ ]:
df['Age']=df['Age'].astype(int)
df

  Employee_ID      Name  Age  Gender Department  Salary       City
0        E101     Akash   25       M         IT   45000  Bengaluru
1        E102     Megha   25       F         HR   38000    Chennai
2        E103      John   28    Male    Finance   55000        NaN
3         NaN     Kavya   25  Female         IT   48000     Mysuru
4        E105    Darshi   26    Male      Sales   25000  Bengaluru
5        E106   Supriya   25  Female         HR  -38000    Chennai
6        E107    Darshi   26    Male      Sales   25000  Bengaluru
7        E108     Sneha   23     NaN         IT   47000      Delhi
8        E109       NaN   25  Female    Finance   52000  Hyderabad
9        E110     Vikas   22    Male         IT   99999    Chennai

In [ ]:
df['Salary']=df['Salary'].astype(int)
df

  Employee_ID      Name  Age  Gender Department  Salary       City
0        E101     Akash   25       M         IT   45000  Bengaluru
1        E102     Megha   25       F         HR   38000    Chennai
2        E103      John   28    Male    Finance   55000        NaN
3         NaN     Kavya   25  Female         IT   48000     Mysuru
4        E105    Darshi   26    Male      Sales   25000  Bengaluru
5        E106   Supriya   25  Female         HR  -38000    Chennai
6        E107    Darshi   26    Male      Sales   25000  Bengaluru
7        E108     Sneha   23     NaN         IT   47000      Delhi
8        E109       NaN   25  Female    Finance   52000  Hyderabad
9        E110     Vikas   22    Male         IT   99999    Chennai

In [ ]:
df.dtypes

Employee_ID    object
Name           object
Age             int64
Gender         object
Department     object
Salary          int64
City           object
dtype: object

In [ ]:
df['Gender']=df['Gender'].replace({"M":"Male","F":"Female"})
df

  Employee_ID      Name  Age  Gender Department  Salary       City
0        E101     Akash   25    Male         IT   45000  Bengaluru
1        E102     Megha   25  Female         HR   38000    Chennai
2        E103      John   28    Male    Finance   55000        NaN
3         NaN     Kavya   25  Female         IT   48000     Mysuru
4        E105    Darshi   26    Male      Sales   25000  Bengaluru
5        E106   Supriya   25  Female         HR  -38000    Chennai
6        E107    Darshi   26    Male      Sales   25000  Bengaluru
7        E108     Sneha   23     NaN         IT   47000      Delhi
8        E109       NaN   25  Female    Finance   52000  Hyderabad
9        E110     Vikas   22    Male         IT   99999    Chennai

In [ ]:
df=pd.get_dummies(df,columns=['Gender'],dtype=int)
df

,Employee_ID,Name,Age,Department,Salary,City,Gender_Female,Gender_Male
0,E101,Akash,25,IT,45000,Bengaluru,0,1
1,E102,Megha,25,HR,38000,Chennai,1,0
2,E103,John,28,Finance,55000,NaN,0,1
3,NaN,Kavya,25,IT,48000,Mysuru,1,0
4,E105,Darshi,26,Sales,25000,Bengaluru,0,1
5,E106,Supriya,25,HR,-38000,Chennai,1,0
6,E107,Darshi,26,Sales,25000,Bengaluru,0,1
7,E108,Sneha,23,IT,47000,Delhi,0,0
8,E109,NaN,25,Finance,52000,Hyderabad,1,0
9,E110,Vikas,22,IT,99999,Chennai,0,1