In [ ]:
# 2)data cleaning and exploratory data analysis
import pandas as pd
data=pd.read_excel("/content/book1.xlsx")
data

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-06-12
1,S202,Priya,NaN,Female,BBA,78.0,Chennai,2023-07-15
2,S203,Arjun,21.0,Male,BCA,92.0,Hyderabad,2023-08-10
3,S204,Sneha,19.0,F,MCA,88.0,Mysuru,2023-06-20
4,S205,Kiran,150.0,Male,BBA,65.0,Bengaluru,2023-07-10
5,S206,Anjali,22.0,Female,BCA,-45.0,Chennai,2023-07-15
6,NaN,Ravi,21.0,M,MCA,95.0,Delhi,2023-08-01
7,S208,NaN,20.0,Female,BCA,72.0,Hyderabad,2023-08-22
8,S209,Manju,-19.0,F,BBA,80.0,Bengaluru,2023-07-10
9,S210,Suresh,22.0,Male,MCA,89.0,Chennai,2023-08-05
10,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-06-12
11,S212,Divya,21.0,Female,NaN,76.0,Mysuru,2023-07-18
12,S213,Naveen,22.0,Male,BCA,NaN,Hyderabad,2023-08-25
13,S214,Pooja,20.0,Female,BBA,68.0,NaN,2023-07-12
14,S215,Mahesh,23.0,Male,MCA,105.0,Bengaluru,2023-06-30

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student_ID      14 non-null     object
 1   Name            14 non-null     object
 2   Age             14 non-null     float64
 3   Gender          15 non-null     object
 4   Course          14 non-null     object
 5   Marks           14 non-null     float64
 6   City            14 non-null     object
 7   Admission_Date  15 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(5)
memory usage: 1.1+ KB

In [ ]:
data.dtypes

Student_ID                object
Name                      object
Age                      float64
Gender                    object
Course                    object
Marks                    float64
City                      object
Admission_Date    datetime64[ns]
dtype: object

In [ ]:
data.head()

  Student_ID   Name    Age  Gender Course  Marks       City Admission_Date
0       S201  Rahul   20.0       M    BCA   85.0  Bengaluru     2023-06-12
1       S202  Priya    NaN  Female    BBA   78.0    Chennai     2023-07-15
2       S203  Arjun   21.0    Male    BCA   92.0  Hyderabad     2023-08-10
3       S204  Sneha   19.0       F    MCA   88.0     Mysuru     2023-06-20
4       S205  Kiran  150.0    Male    BBA   65.0  Bengaluru     2023-07-10

In [ ]:
data.tail()

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
10,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-06-12
11,S212,Divya,21.0,Female,NaN,76.0,Mysuru,2023-07-18
12,S213,Naveen,22.0,Male,BCA,NaN,Hyderabad,2023-08-25
13,S214,Pooja,20.0,Female,BBA,68.0,NaN,2023-07-12
14,S215,Mahesh,23.0,Male,MCA,105.0,Bengaluru,2023-06-30

In [ ]:
data.isnull()

    Student_ID   Name    Age  Gender  Course  Marks   City  Admission_Date
0        False  False  False   False   False  False  False           False
1        False  False   True   False   False  False  False           False
2        False  False  False   False   False  False  False           False
3        False  False  False   False   False  False  False           False
4        False  False  False   False   False  False  False           False
5        False  False  False   False   False  False  False           False
6         True  False  False   False   False  False  False           False
7        False   True  False   False   False  False  False           False
8        False  False  False   False   False  False  False           False
9        False  False  False   False   False  False  False           False
10       False  False  False   False   False  False  False           False
11       False  False  False   False    True  False  False           False
12       False  False  False   False   False   True  False           False
13       False  False  False   False   False  False   True           False
14       False  False  False   False   False  False  False           False

In [ ]:
data.isnull().sum()

Student_ID        1
Name              1
Age               1
Gender            0
Course            1
Marks             1
City              1
Admission_Date    0
dtype: int64

In [ ]:
data.isnull().sum().sum()

np.int64(6)

In [ ]:
data.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13    False
14    False
dtype: bool

In [ ]:
data.duplicated().sum()

np.int64(1)

In [ ]:
data.drop_duplicates()

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-06-12
1,S202,Priya,NaN,Female,BBA,78.0,Chennai,2023-07-15
2,S203,Arjun,21.0,Male,BCA,92.0,Hyderabad,2023-08-10
3,S204,Sneha,19.0,F,MCA,88.0,Mysuru,2023-06-20
4,S205,Kiran,150.0,Male,BBA,65.0,Bengaluru,2023-07-10
5,S206,Anjali,22.0,Female,BCA,-45.0,Chennai,2023-07-15
6,NaN,Ravi,21.0,M,MCA,95.0,Delhi,2023-08-01
7,S208,NaN,20.0,Female,BCA,72.0,Hyderabad,2023-08-22
8,S209,Manju,-19.0,F,BBA,80.0,Bengaluru,2023-07-10
9,S210,Suresh,22.0,Male,MCA,89.0,Chennai,2023-08-05
11,S212,Divya,21.0,Female,NaN,76.0,Mysuru,2023-07-18
12,S213,Naveen,22.0,Male,BCA,NaN,Hyderabad,2023-08-25
13,S214,Pooja,20.0,Female,BBA,68.0,NaN,2023-07-12
14,S215,Mahesh,23.0,Male,MCA,105.0,Bengaluru,2023-06-30

In [ ]:
data['Student_ID']=data['Student_ID'].fillna('S207')
data

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-06-12
1,S202,Priya,NaN,Female,BBA,78.0,Chennai,2023-07-15
2,S203,Arjun,21.0,Male,BCA,92.0,Hyderabad,2023-08-10
3,S204,Sneha,19.0,F,MCA,88.0,Mysuru,2023-06-20
4,S205,Kiran,150.0,Male,BBA,65.0,Bengaluru,2023-07-10
5,S206,Anjali,22.0,Female,BCA,-45.0,Chennai,2023-07-15
6,S207,Ravi,21.0,M,MCA,95.0,Delhi,2023-08-01
7,S208,NaN,20.0,Female,BCA,72.0,Hyderabad,2023-08-22
8,S209,Manju,-19.0,F,BBA,80.0,Bengaluru,2023-07-10
9,S210,Suresh,22.0,Male,MCA,89.0,Chennai,2023-08-05
10,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-06-12
11,S212,Divya,21.0,Female,NaN,76.0,Mysuru,2023-07-18
12,S213,Naveen,22.0,Male,BCA,NaN,Hyderabad,2023-08-25
13,S214,Pooja,20.0,Female,BBA,68.0,NaN,2023-07-12
14,S215,Mahesh,23.0,Male,MCA,105.0,Bengaluru,2023-06-30

In [ ]:
data['Name']=data['Name'].ffill()
data

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-06-12
1,S202,Priya,NaN,Female,BBA,78.0,Chennai,2023-07-15
2,S203,Arjun,21.0,Male,BCA,92.0,Hyderabad,2023-08-10
3,S204,Sneha,19.0,F,MCA,88.0,Mysuru,2023-06-20
4,S205,Kiran,150.0,Male,BBA,65.0,Bengaluru,2023-07-10
5,S206,Anjali,22.0,Female,BCA,-45.0,Chennai,2023-07-15
6,S207,Ravi,21.0,M,MCA,95.0,Delhi,2023-08-01
7,S208,Ravi,20.0,Female,BCA,72.0,Hyderabad,2023-08-22
8,S209,Manju,-19.0,F,BBA,80.0,Bengaluru,2023-07-10
9,S210,Suresh,22.0,Male,MCA,89.0,Chennai,2023-08-05
10,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-06-12
11,S212,Divya,21.0,Female,NaN,76.0,Mysuru,2023-07-18
12,S213,Naveen,22.0,Male,BCA,NaN,Hyderabad,2023-08-25
13,S214,Pooja,20.0,Female,BBA,68.0,NaN,2023-07-12
14,S215,Mahesh,23.0,Male,MCA,105.0,Bengaluru,2023-06-30

In [ ]:
data['Age']=data['Age'].bfill()
data

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-06-12
1,S202,Priya,21.0,Female,BBA,78.0,Chennai,2023-07-15
2,S203,Arjun,21.0,Male,BCA,92.0,Hyderabad,2023-08-10
3,S204,Sneha,19.0,F,MCA,88.0,Mysuru,2023-06-20
4,S205,Kiran,150.0,Male,BBA,65.0,Bengaluru,2023-07-10
5,S206,Anjali,22.0,Female,BCA,-45.0,Chennai,2023-07-15
6,S207,Ravi,21.0,M,MCA,95.0,Delhi,2023-08-01
7,S208,Ravi,20.0,Female,BCA,72.0,Hyderabad,2023-08-22
8,S209,Manju,-19.0,F,BBA,80.0,Bengaluru,2023-07-10
9,S210,Suresh,22.0,Male,MCA,89.0,Chennai,2023-08-05
10,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-06-12
11,S212,Divya,21.0,Female,NaN,76.0,Mysuru,2023-07-18
12,S213,Naveen,22.0,Male,BCA,NaN,Hyderabad,2023-08-25
13,S214,Pooja,20.0,Female,BBA,68.0,NaN,2023-07-12
14,S215,Mahesh,23.0,Male,MCA,105.0,Bengaluru,2023-06-30

In [ ]:
data['Course']=data['Course'].fillna('BCA')
data

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-06-12
1,S202,Priya,21.0,Female,BBA,78.0,Chennai,2023-07-15
2,S203,Arjun,21.0,Male,BCA,92.0,Hyderabad,2023-08-10
3,S204,Sneha,19.0,F,MCA,88.0,Mysuru,2023-06-20
4,S205,Kiran,150.0,Male,BBA,65.0,Bengaluru,2023-07-10
5,S206,Anjali,22.0,Female,BCA,-45.0,Chennai,2023-07-15
6,S207,Ravi,21.0,M,MCA,95.0,Delhi,2023-08-01
7,S208,Ravi,20.0,Female,BCA,72.0,Hyderabad,2023-08-22
8,S209,Manju,-19.0,F,BBA,80.0,Bengaluru,2023-07-10
9,S210,Suresh,22.0,Male,MCA,89.0,Chennai,2023-08-05
10,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-06-12
11,S212,Divya,21.0,Female,BCA,76.0,Mysuru,2023-07-18
12,S213,Naveen,22.0,Male,BCA,NaN,Hyderabad,2023-08-25
13,S214,Pooja,20.0,Female,BBA,68.0,NaN,2023-07-12
14,S215,Mahesh,23.0,Male,MCA,105.0,Bengaluru,2023-06-30

In [ ]:
data['City']=data['City'].ffill()
data

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-06-12
1,S202,Priya,21.0,Female,BBA,78.0,Chennai,2023-07-15
2,S203,Arjun,21.0,Male,BCA,92.0,Hyderabad,2023-08-10
3,S204,Sneha,19.0,F,MCA,88.0,Mysuru,2023-06-20
4,S205,Kiran,150.0,Male,BBA,65.0,Bengaluru,2023-07-10
5,S206,Anjali,22.0,Female,BCA,-45.0,Chennai,2023-07-15
6,S207,Ravi,21.0,M,MCA,95.0,Delhi,2023-08-01
7,S208,Ravi,20.0,Female,BCA,72.0,Hyderabad,2023-08-22
8,S209,Manju,-19.0,F,BBA,80.0,Bengaluru,2023-07-10
9,S210,Suresh,22.0,Male,MCA,89.0,Chennai,2023-08-05
10,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-06-12
11,S212,Divya,21.0,Female,BCA,76.0,Mysuru,2023-07-18
12,S213,Naveen,22.0,Male,BCA,NaN,Hyderabad,2023-08-25
13,S214,Pooja,20.0,Female,BBA,68.0,Hyderabad,2023-07-12
14,S215,Mahesh,23.0,Male,MCA,105.0,Bengaluru,2023-06-30

In [ ]:
data.isnull().sum()

Student_ID        0
Name              0
Age               0
Gender            0
Course            0
Marks             1
City              0
Admission_Date    0
dtype: int64

In [ ]:
data.drop_duplicates()

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-06-12
1,S202,Priya,21.0,Female,BBA,78.0,Chennai,2023-07-15
2,S203,Arjun,21.0,Male,BCA,92.0,Hyderabad,2023-08-10
3,S204,Sneha,19.0,F,MCA,88.0,Mysuru,2023-06-20
4,S205,Kiran,150.0,Male,BBA,65.0,Bengaluru,2023-07-10
5,S206,Anjali,22.0,Female,BCA,-45.0,Chennai,2023-07-15
6,S207,Ravi,21.0,M,MCA,95.0,Delhi,2023-08-01
7,S208,Ravi,20.0,Female,BCA,72.0,Hyderabad,2023-08-22
8,S209,Manju,-19.0,F,BBA,80.0,Bengaluru,2023-07-10
9,S210,Suresh,22.0,Male,MCA,89.0,Chennai,2023-08-05
11,S212,Divya,21.0,Female,BCA,76.0,Mysuru,2023-07-18
12,S213,Naveen,22.0,Male,BCA,NaN,Hyderabad,2023-08-25
13,S214,Pooja,20.0,Female,BBA,68.0,Hyderabad,2023-07-12
14,S215,Mahesh,23.0,Male,MCA,105.0,Bengaluru,2023-06-30

In [ ]:
import numpy as np
data.loc[data['Age']>90,'Age']=np.nan
data

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-06-12
1,S202,Priya,21.0,Female,BBA,78.0,Chennai,2023-07-15
2,S203,Arjun,21.0,Male,BCA,92.0,Hyderabad,2023-08-10
3,S204,Sneha,19.0,F,MCA,88.0,Mysuru,2023-06-20
4,S205,Kiran,NaN,Male,BBA,65.0,Bengaluru,2023-07-10
5,S206,Anjali,22.0,Female,BCA,-45.0,Chennai,2023-07-15
6,S207,Ravi,21.0,M,MCA,95.0,Delhi,2023-08-01
7,S208,Ravi,20.0,Female,BCA,72.0,Hyderabad,2023-08-22
8,S209,Manju,-19.0,F,BBA,80.0,Bengaluru,2023-07-10
9,S210,Suresh,22.0,Male,MCA,89.0,Chennai,2023-08-05
10,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-06-12
11,S212,Divya,21.0,Female,BCA,76.0,Mysuru,2023-07-18
12,S213,Naveen,22.0,Male,BCA,NaN,Hyderabad,2023-08-25
13,S214,Pooja,20.0,Female,BBA,68.0,Hyderabad,2023-07-12
14,S215,Mahesh,23.0,Male,MCA,105.0,Bengaluru,2023-06-30

In [ ]:
data.loc[data['Age']<0,'Age']=np.nan
data

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-06-12
1,S202,Priya,21.0,Female,BBA,78.0,Chennai,2023-07-15
2,S203,Arjun,21.0,Male,BCA,92.0,Hyderabad,2023-08-10
3,S204,Sneha,19.0,F,MCA,88.0,Mysuru,2023-06-20
4,S205,Kiran,NaN,Male,BBA,65.0,Bengaluru,2023-07-10
5,S206,Anjali,22.0,Female,BCA,-45.0,Chennai,2023-07-15
6,S207,Ravi,21.0,M,MCA,95.0,Delhi,2023-08-01
7,S208,Ravi,20.0,Female,BCA,72.0,Hyderabad,2023-08-22
8,S209,Manju,NaN,F,BBA,80.0,Bengaluru,2023-07-10
9,S210,Suresh,22.0,Male,MCA,89.0,Chennai,2023-08-05
10,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-06-12
11,S212,Divya,21.0,Female,BCA,76.0,Mysuru,2023-07-18
12,S213,Naveen,22.0,Male,BCA,NaN,Hyderabad,2023-08-25
13,S214,Pooja,20.0,Female,BBA,68.0,Hyderabad,2023-07-12
14,S215,Mahesh,23.0,Male,MCA,105.0,Bengaluru,2023-06-30

In [ ]:
data.loc[data['Marks']<0,'Marks']=np.nan
data

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-06-12
1,S202,Priya,21.0,Female,BBA,78.0,Chennai,2023-07-15
2,S203,Arjun,21.0,Male,BCA,92.0,Hyderabad,2023-08-10
3,S204,Sneha,19.0,F,MCA,88.0,Mysuru,2023-06-20
4,S205,Kiran,NaN,Male,BBA,65.0,Bengaluru,2023-07-10
5,S206,Anjali,22.0,Female,BCA,NaN,Chennai,2023-07-15
6,S207,Ravi,21.0,M,MCA,95.0,Delhi,2023-08-01
7,S208,Ravi,20.0,Female,BCA,72.0,Hyderabad,2023-08-22
8,S209,Manju,NaN,F,BBA,80.0,Bengaluru,2023-07-10
9,S210,Suresh,22.0,Male,MCA,89.0,Chennai,2023-08-05
10,S201,Rahul,20.0,M,BCA,85.0,Bengaluru,2023-06-12
11,S212,Divya,21.0,Female,BCA,76.0,Mysuru,2023-07-18
12,S213,Naveen,22.0,Male,BCA,NaN,Hyderabad,2023-08-25
13,S214,Pooja,20.0,Female,BBA,68.0,Hyderabad,2023-07-12
14,S215,Mahesh,23.0,Male,MCA,105.0,Bengaluru,2023-06-30

In [ ]:
data['Age']=data['Age'].fillna(data['Age'].mean())
data

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20.000000,M,BCA,85.0,Bengaluru,2023-06-12
1,S202,Priya,21.000000,Female,BBA,78.0,Chennai,2023-07-15
2,S203,Arjun,21.000000,Male,BCA,92.0,Hyderabad,2023-08-10
3,S204,Sneha,19.000000,F,MCA,88.0,Mysuru,2023-06-20
4,S205,Kiran,20.923077,Male,BBA,65.0,Bengaluru,2023-07-10
5,S206,Anjali,22.000000,Female,BCA,NaN,Chennai,2023-07-15
6,S207,Ravi,21.000000,M,MCA,95.0,Delhi,2023-08-01
7,S208,Ravi,20.000000,Female,BCA,72.0,Hyderabad,2023-08-22
8,S209,Manju,20.923077,F,BBA,80.0,Bengaluru,2023-07-10
9,S210,Suresh,22.000000,Male,MCA,89.0,Chennai,2023-08-05
10,S201,Rahul,20.000000,M,BCA,85.0,Bengaluru,2023-06-12
11,S212,Divya,21.000000,Female,BCA,76.0,Mysuru,2023-07-18
12,S213,Naveen,22.000000,Male,BCA,NaN,Hyderabad,2023-08-25
13,S214,Pooja,20.000000,Female,BBA,68.0,Hyderabad,2023-07-12
14,S215,Mahesh,23.000000,Male,MCA,105.0,Bengaluru,2023-06-30

In [ ]:
data['Marks']=data['Marks'].fillna(data['Marks'].mean())
data

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20.000000,M,BCA,85.000000,Bengaluru,2023-06-12
1,S202,Priya,21.000000,Female,BBA,78.000000,Chennai,2023-07-15
2,S203,Arjun,21.000000,Male,BCA,92.000000,Hyderabad,2023-08-10
3,S204,Sneha,19.000000,F,MCA,88.000000,Mysuru,2023-06-20
4,S205,Kiran,20.923077,Male,BBA,65.000000,Bengaluru,2023-07-10
5,S206,Anjali,22.000000,Female,BCA,82.923077,Chennai,2023-07-15
6,S207,Ravi,21.000000,M,MCA,95.000000,Delhi,2023-08-01
7,S208,Ravi,20.000000,Female,BCA,72.000000,Hyderabad,2023-08-22
8,S209,Manju,20.923077,F,BBA,80.000000,Bengaluru,2023-07-10
9,S210,Suresh,22.000000,Male,MCA,89.000000,Chennai,2023-08-05
10,S201,Rahul,20.000000,M,BCA,85.000000,Bengaluru,2023-06-12
11,S212,Divya,21.000000,Female,BCA,76.000000,Mysuru,2023-07-18
12,S213,Naveen,22.000000,Male,BCA,82.923077,Hyderabad,2023-08-25
13,S214,Pooja,20.000000,Female,BBA,68.000000,Hyderabad,2023-07-12
14,S215,Mahesh,23.000000,Male,MCA,105.000000,Bengaluru,2023-06-30

In [ ]:
data['Age']=data['Age'].astype(int)
data

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20,M,BCA,85.000000,Bengaluru,2023-06-12
1,S202,Priya,21,Female,BBA,78.000000,Chennai,2023-07-15
2,S203,Arjun,21,Male,BCA,92.000000,Hyderabad,2023-08-10
3,S204,Sneha,19,F,MCA,88.000000,Mysuru,2023-06-20
4,S205,Kiran,20,Male,BBA,65.000000,Bengaluru,2023-07-10
5,S206,Anjali,22,Female,BCA,82.923077,Chennai,2023-07-15
6,S207,Ravi,21,M,MCA,95.000000,Delhi,2023-08-01
7,S208,Ravi,20,Female,BCA,72.000000,Hyderabad,2023-08-22
8,S209,Manju,20,F,BBA,80.000000,Bengaluru,2023-07-10
9,S210,Suresh,22,Male,MCA,89.000000,Chennai,2023-08-05
10,S201,Rahul,20,M,BCA,85.000000,Bengaluru,2023-06-12
11,S212,Divya,21,Female,BCA,76.000000,Mysuru,2023-07-18
12,S213,Naveen,22,Male,BCA,82.923077,Hyderabad,2023-08-25
13,S214,Pooja,20,Female,BBA,68.000000,Hyderabad,2023-07-12
14,S215,Mahesh,23,Male,MCA,105.000000,Bengaluru,2023-06-30

In [ ]:
data['Marks']=data['Marks'].astype(int)
data

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20,M,BCA,85,Bengaluru,2023-06-12
1,S202,Priya,21,Female,BBA,78,Chennai,2023-07-15
2,S203,Arjun,21,Male,BCA,92,Hyderabad,2023-08-10
3,S204,Sneha,19,F,MCA,88,Mysuru,2023-06-20
4,S205,Kiran,20,Male,BBA,65,Bengaluru,2023-07-10
5,S206,Anjali,22,Female,BCA,82,Chennai,2023-07-15
6,S207,Ravi,21,M,MCA,95,Delhi,2023-08-01
7,S208,Ravi,20,Female,BCA,72,Hyderabad,2023-08-22
8,S209,Manju,20,F,BBA,80,Bengaluru,2023-07-10
9,S210,Suresh,22,Male,MCA,89,Chennai,2023-08-05
10,S201,Rahul,20,M,BCA,85,Bengaluru,2023-06-12
11,S212,Divya,21,Female,BCA,76,Mysuru,2023-07-18
12,S213,Naveen,22,Male,BCA,82,Hyderabad,2023-08-25
13,S214,Pooja,20,Female,BBA,68,Hyderabad,2023-07-12
14,S215,Mahesh,23,Male,MCA,105,Bengaluru,2023-06-30

In [ ]:
data['Gender']=data['Gender'].replace({"M":"Male","F":"Female"})
data

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20,Male,BCA,85,Bengaluru,2023-06-12
1,S202,Priya,21,Female,BBA,78,Chennai,2023-07-15
2,S203,Arjun,21,Male,BCA,92,Hyderabad,2023-08-10
3,S204,Sneha,19,Female,MCA,88,Mysuru,2023-06-20
4,S205,Kiran,20,Male,BBA,65,Bengaluru,2023-07-10
5,S206,Anjali,22,Female,BCA,82,Chennai,2023-07-15
6,S207,Ravi,21,Male,MCA,95,Delhi,2023-08-01
7,S208,Ravi,20,Female,BCA,72,Hyderabad,2023-08-22
8,S209,Manju,20,Female,BBA,80,Bengaluru,2023-07-10
9,S210,Suresh,22,Male,MCA,89,Chennai,2023-08-05
10,S201,Rahul,20,Male,BCA,85,Bengaluru,2023-06-12
11,S212,Divya,21,Female,BCA,76,Mysuru,2023-07-18
12,S213,Naveen,22,Male,BCA,82,Hyderabad,2023-08-25
13,S214,Pooja,20,Female,BBA,68,Hyderabad,2023-07-12
14,S215,Mahesh,23,Male,MCA,105,Bengaluru,2023-06-30

In [ ]:
data.describe()

             Age       Marks       Admission_Date
count  15.000000   15.000000                   15
mean   20.800000   82.800000  2023-07-16 19:12:00
min    19.000000   65.000000  2023-06-12 00:00:00
25%    20.000000   77.000000  2023-07-05 00:00:00
50%    21.000000   82.000000  2023-07-15 00:00:00
75%    21.500000   88.500000  2023-08-03 00:00:00
max    23.000000  105.000000  2023-08-25 00:00:00
std     1.082326   10.462177                  NaN

In [ ]:
data['Name']=data['Name'].str.strip()
data

,Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date
0,S201,Rahul,20,Male,BCA,85,Bengaluru,2023-06-12
1,S202,Priya,21,Female,BBA,78,Chennai,2023-07-15
2,S203,Arjun,21,Male,BCA,92,Hyderabad,2023-08-10
3,S204,Sneha,19,Female,MCA,88,Mysuru,2023-06-20
4,S205,Kiran,20,Male,BBA,65,Bengaluru,2023-07-10
5,S206,Anjali,22,Female,BCA,82,Chennai,2023-07-15
6,S207,Ravi,21,Male,MCA,95,Delhi,2023-08-01
7,S208,Ravi,20,Female,BCA,72,Hyderabad,2023-08-22
8,S209,Manju,20,Female,BBA,80,Bengaluru,2023-07-10
9,S210,Suresh,22,Male,MCA,89,Chennai,2023-08-05
10,S201,Rahul,20,Male,BCA,85,Bengaluru,2023-06-12
11,S212,Divya,21,Female,BCA,76,Mysuru,2023-07-18
12,S213,Naveen,22,Male,BCA,82,Hyderabad,2023-08-25
13,S214,Pooja,20,Female,BBA,68,Hyderabad,2023-07-12
14,S215,Mahesh,23,Male,MCA,105,Bengaluru,2023-06-30

In [ ]:
data.shape

(15, 8)

In [ ]:
data['Marks'].max()

105

In [ ]:
data['Marks'].min()

65

In [ ]:
data['Marks'].mean()

np.float64(82.8)

In [ ]:
data['Marks'].sum()

np.int64(1242)

In [ ]:
data.to_csv()

',Student_ID,Name,Age,Gender,Course,Marks,City,Admission_Date\n0,S201,Rahul,20,Male,BCA,85,Bengaluru,2023-06-12\n1,S202,Priya,21,Female,BBA,78,Chennai,2023-07-15\n2,S203,Arjun,21,Male,BCA,92,Hyderabad,2023-08-10\n3,S204,Sneha,19,Female,MCA,88,Mysuru,2023-06-20\n4,S205,Kiran,20,Male,BBA,65,Bengaluru,2023-07-10\n5,S206,Anjali,22,Female,  BCA,82,Chennai,2023-07-15\n6,S207,Ravi,21,Male,MCA,95,Delhi,2023-08-01\n7,S208,Ravi,20,Female,BCA,72,Hyderabad,2023-08-22\n8,S209,Manju,20,Female,BBA,80,Bengaluru,2023-07-10\n9,S210,Suresh,22,Male,MCA,89,Chennai,2023-08-05\n10,S201,Rahul,20,Male,BCA,85,Bengaluru,2023-06-12\n11,S212,Divya,21,Female,BCA,76,Mysuru,2023-07-18\n12,S213,Naveen,22,Male,BCA,82,  Hyderabad,2023-08-25\n13,S214,Pooja,20,   Female,BBA,68,  Hyderabad,2023-07-12\n14,S215,Mahesh,23,Male,MCA,105,Bengaluru,2023-06-30\n'

In [ ]:
data=data.drop('Admission_Date',axis=1)
data

   Student_ID    Name  Age     Gender Course  Marks         City
0        S201   Rahul   20       Male    BCA     85    Bengaluru
1        S202   Priya   21     Female    BBA     78      Chennai
2        S203   Arjun   21       Male    BCA     92    Hyderabad
3        S204   Sneha   19     Female    MCA     88       Mysuru
4        S205   Kiran   20       Male    BBA     65    Bengaluru
5        S206  Anjali   22     Female    BCA     82      Chennai
6        S207    Ravi   21       Male    MCA     95        Delhi
7        S208    Ravi   20     Female    BCA     72    Hyderabad
8        S209   Manju   20     Female    BBA     80    Bengaluru
9        S210  Suresh   22       Male    MCA     89      Chennai
10       S201   Rahul   20       Male    BCA     85    Bengaluru
11       S212   Divya   21     Female    BCA     76       Mysuru
12       S213  Naveen   22       Male    BCA     82    Hyderabad
13       S214   Pooja   20     Female    BBA     68    Hyderabad
14       S215  Mahesh   23       Male    MCA    105    Bengaluru

In [ ]:
data.dropna()

   Student_ID    Name  Age     Gender Course  Marks         City
0        S201   Rahul   20       Male    BCA     85    Bengaluru
1        S202   Priya   21     Female    BBA     78      Chennai
2        S203   Arjun   21       Male    BCA     92    Hyderabad
3        S204   Sneha   19     Female    MCA     88       Mysuru
4        S205   Kiran   20       Male    BBA     65    Bengaluru
5        S206  Anjali   22     Female    BCA     82      Chennai
6        S207    Ravi   21       Male    MCA     95        Delhi
7        S208    Ravi   20     Female    BCA     72    Hyderabad
8        S209   Manju   20     Female    BBA     80    Bengaluru
9        S210  Suresh   22       Male    MCA     89      Chennai
10       S201   Rahul   20       Male    BCA     85    Bengaluru
11       S212   Divya   21     Female    BCA     76       Mysuru
12       S213  Naveen   22       Male    BCA     82    Hyderabad
13       S214   Pooja   20     Female    BBA     68    Hyderabad
14       S215  Mahesh   23       Male    MCA    105    Bengaluru

In [ ]:
data.describe()

             Age       Marks
count  15.000000   15.000000
mean   20.800000   82.800000
std     1.082326   10.462177
min    19.000000   65.000000
25%    20.000000   77.000000
50%    21.000000   82.000000
75%    21.500000   88.500000
max    23.000000  105.000000

In [ ]:
data.shape

(15, 7)

In [ ]:
data['Marks'].median()

82.0

In [ ]:
print(data['Course'].unique())

['BCA' 'BBA' 'MCA' '  BCA']

In [ ]:
print(data['Course'].value_counts())

Course
BCA      6
BBA      4
MCA      4
  BCA    1
Name: count, dtype: int64

In [ ]:
data.drop_duplicates()

   Student_ID    Name  Age     Gender Course  Marks         City
0        S201   Rahul   20       Male    BCA     85    Bengaluru
1        S202   Priya   21     Female    BBA     78      Chennai
2        S203   Arjun   21       Male    BCA     92    Hyderabad
3        S204   Sneha   19     Female    MCA     88       Mysuru
4        S205   Kiran   20       Male    BBA     65    Bengaluru
5        S206  Anjali   22     Female    BCA     82      Chennai
6        S207    Ravi   21       Male    MCA     95        Delhi
7        S208    Ravi   20     Female    BCA     72    Hyderabad
8        S209   Manju   20     Female    BBA     80    Bengaluru
9        S210  Suresh   22       Male    MCA     89      Chennai
11       S212   Divya   21     Female    BCA     76       Mysuru
12       S213  Naveen   22       Male    BCA     82    Hyderabad
13       S214   Pooja   20     Female    BBA     68    Hyderabad
14       S215  Mahesh   23       Male    MCA    105    Bengaluru

In [ ]:
data.interpolate()

/tmp/ipykernel_6673/982976692.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  data.interpolate()

   Student_ID    Name  Age     Gender Course  Marks         City
0        S201   Rahul   20       Male    BCA     85    Bengaluru
1        S202   Priya   21     Female    BBA     78      Chennai
2        S203   Arjun   21       Male    BCA     92    Hyderabad
3        S204   Sneha   19     Female    MCA     88       Mysuru
4        S205   Kiran   20       Male    BBA     65    Bengaluru
5        S206  Anjali   22     Female    BCA     82      Chennai
6        S207    Ravi   21       Male    MCA     95        Delhi
7        S208    Ravi   20     Female    BCA     72    Hyderabad
8        S209   Manju   20     Female    BBA     80    Bengaluru
9        S210  Suresh   22       Male    MCA     89      Chennai
10       S201   Rahul   20       Male    BCA     85    Bengaluru
11       S212   Divya   21     Female    BCA     76       Mysuru
12       S213  Naveen   22       Male    BCA     82    Hyderabad
13       S214   Pooja   20     Female    BBA     68    Hyderabad
14       S215  Mahesh   23       Male    MCA    105    Bengaluru

In [ ]:
data.ffill()

   Student_ID    Name  Age     Gender Course  Marks         City
0        S201   Rahul   20       Male    BCA     85    Bengaluru
1        S202   Priya   21     Female    BBA     78      Chennai
2        S203   Arjun   21       Male    BCA     92    Hyderabad
3        S204   Sneha   19     Female    MCA     88       Mysuru
4        S205   Kiran   20       Male    BBA     65    Bengaluru
5        S206  Anjali   22     Female    BCA     82      Chennai
6        S207    Ravi   21       Male    MCA     95        Delhi
7        S208    Ravi   20     Female    BCA     72    Hyderabad
8        S209   Manju   20     Female    BBA     80    Bengaluru
9        S210  Suresh   22       Male    MCA     89      Chennai
10       S201   Rahul   20       Male    BCA     85    Bengaluru
11       S212   Divya   21     Female    BCA     76       Mysuru
12       S213  Naveen   22       Male    BCA     82    Hyderabad
13       S214   Pooja   20     Female    BBA     68    Hyderabad
14       S215  Mahesh   23       Male    MCA    105    Bengaluru