In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
print(pd.__version__)

2.2.3

In [ ]:
import pandas as pd
marks=pd.Series ([10,20,30,40,50])
print(marks)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
#dictionary to pandas Series
import pandas as pd
student={'Rahul':86,
         'Reg_no':121,
         'place':"Gadag",
         'college':"kle",
         'Result':"pass",
         'year':2020,
         }
s=pd.Series(student)
s

Rahul         86
Reg_no       121
place      Gadag
college      kle
Result      pass
year        2020
dtype: object

In [ ]:
#dictionary to pandas Series
import pandas as pd
student={'Rahul':86,
         'Reg_no':121,
         'place':"Gadag",
         'college':"kle",
         'Result':"pass",
         'year':2020,
         }
s=pd.Series(student)
s
print(s[1])
print(s['Result'])
print(s['place'])
print(s['college'])
print(s['year'])
print(s[-2])

121
pass
Gadag
kle
2020
pass

/tmp/ipykernel_735/2671213870.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[1])
/tmp/ipykernel_735/2671213870.py:17: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[-2])

In [ ]:
#list to pandas series
import pandas as pd
num=[12,14,52,71,83,65,22]
data=pd.Series(num)
data

0    12
1    14
2    52
3    71
4    83
5    65
6    22
dtype: int64

In [ ]:
#tuple to pandas Series
import pandas as pd
num=(1,2,3,4,5,6,8)
data=pd.Series(num)
data

0    1
1    2
2    3
3    4
4    5
5    6
6    8
dtype: int64

In [ ]:
import pandas as pd
marks=pd.Series([85,90,75,95,80])
print(marks[1:4])

1    90
2    75
3    95
dtype: int64

In [ ]:
import pandas as pd
marks=pd.Series([85,90,75,95,80])
print(marks[0])

85

In [ ]:
import pandas as pd
arr=[86,45,89,34,64,94,12]
data=pd.Series(arr)
data
print(data[data>82])

0    86
2    89
5    94
dtype: int64

In [ ]:
import numpy as np
import pandas as pd
arr = np.array([80,90,100])
arr +=5
arr
new=pd.Series(arr)
new
print(new*2)
print(new[new>80])
print(new.dtype)
print(new.shape)
print(new.size)
print(new.index)
print(new.values)

0    170
1    190
2    210
dtype: int64
0     85
1     95
2    105
dtype: int64
int64
(3,)
3
RangeIndex(start=0, stop=3, step=1)
[ 85  95 105]

In [ ]:
#DataFrame Programs
#1)Dic to DataFrame
import pandas as pd
demo={'Reg No':[11,12,13,14,15,16],
      'Name':['Sahan','Rahul','Anita','Pruthvi','Radha','Bhavana'],
      'Age':[19,20,25,30,29,22],
      'Place':['Gadag','Koppal','Ballari','Kolar','Haveeri','Hassan'],
       'Marks':[90,85,92,78,60,64],
      }
demo
data=pd.DataFrame(demo)
data

   Reg No     Name  Age    Place  Marks
0      11    Sahan   19    Gadag     90
1      12    Rahul   20   Koppal     85
2      13    Anita   25  Ballari     92
3      14  Pruthvi   30    Kolar     78
4      15    Radha   29  Haveeri     60
5      16  Bhavana   22   Hassan     64

In [ ]:
#2)csv file to DataFrame
import pandas as pd
df=pd.read_csv("/content/Employee.csv")
df

   Emp id       Name  salary    company
0     101       Ravi   25000        TCS
1     102     Geetha   40000      Wipro
2     103  Sangeetha  100000    Infosys
3     104      Sindu   50000  Accenture

In [ ]:
df['Name']

0         Ravi
1       Geetha
2    Sangeetha
3        Sindu
Name: Name, dtype: object

In [ ]:
df['salary']

0     25000
1     40000
2    100000
3     50000
Name: salary, dtype: int64

In [ ]:
import pandas as pd
data = pd.read_excel("/content/Teacher.xlsx")
data

    Id   Name Department  Salary
0  101  Rahul         IT   50000
1  102  Anita         HR   45000
2  103   John      Sales   60000
3  104  Kiran         IT   55000

In [ ]:
data['Name']

0    Rahul
1    Anita
2     John
3    Kiran
Name: Name, dtype: object

In [ ]:
data['Department']

0       IT
1       HR
2    Sales
3       IT
Name: Department, dtype: object

In [ ]:
data['Salary']

0    50000
1    45000
2    60000
3    55000
Name: Salary, dtype: int64

In [ ]:
data[['Id','Name']]

    Id   Name
0  101  Rahul
1  102  Anita
2  103   John
3  104  Kiran

In [ ]:
df["Age"]=[20,25,30,21]
df.to_csv("Age",index=False)
data

    Id   Name Department  Salary  Age
0  101  Rahul         IT   50000   20
1  102  Anita         HR   45000   25
2  103   John      Sales   60000   30
3  104  Kiran         IT   55000   21

In [ ]:
df["City"]=['Gadag','Koppal','Hubbali','Udupi']
df.to_csv("City",index=False)
df

   Emp id       Name  salary    company  Age     City
0     101       Ravi   25000        TCS   20    Gadag
1     102     Geetha   40000      Wipro   25   Koppal
2     103  Sangeetha  100000    Infosys   30  Hubbali
3     104      Sindu   50000  Accenture   21    Udupi

In [ ]:
df=df.drop('Age',axis=1)
df

   Emp id       Name  salary    company     City
0     101       Ravi   25000        TCS    Gadag
1     102     Geetha   40000      Wipro   Koppal
2     103  Sangeetha  100000    Infosys  Hubbali
3     104      Sindu   50000  Accenture    Udupi

In [ ]:
df=df.drop('City',axis=1)
df

   Emp id       Name  salary    company
0     101       Ravi   25000        TCS
1     102     Geetha   40000      Wipro
2     103  Sangeetha  100000    Infosys
3     104      Sindu   50000  Accenture

In [ ]:
data.columns

Index(['Id', 'Name', 'Department', 'Salary'], dtype='object')

In [ ]:
data.shape

(4, 4)

In [ ]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
data.dtypes

Id             int64
Name          object
Department    object
Salary         int64
dtype: object

In [ ]:
data.head()

    Id   Name Department  Salary
0  101  Rahul         IT   50000
1  102  Anita         HR   45000
2  103   John      Sales   60000
3  104  Kiran         IT   55000

In [ ]:
data.tail()

    Id   Name Department  Salary
0  101  Rahul         IT   50000
1  102  Anita         HR   45000
2  103   John      Sales   60000
3  104  Kiran         IT   55000

In [ ]:
data.describe()

               Id        Salary
count    4.000000      4.000000
mean   102.500000  52500.000000
std      1.290994   6454.972244
min    101.000000  45000.000000
25%    101.750000  48750.000000
50%    102.500000  52500.000000
75%    103.250000  56250.000000
max    104.000000  60000.000000

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Id          4 non-null      int64
 1   Name        4 non-null      object
 2   Department  4 non-null      object
 3   Salary      4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [ ]:
import pandas as pd
employee={
         'ID':[101,102,103,104],
          'Name':['Rahul','Anita','John','Kiran'],
          'Department':['IT','HR','Sales','It'],
          'Salary':[50000,45000,60000,55000]
          }
df=pd.DataFrame(employee)
df

    ID   Name Department  Salary
0  101  Rahul         IT   50000
1  102  Anita         HR   45000
2  103   John      Sales   60000
3  104  Kiran         It   55000

In [ ]:
print(df['Salary'].mean())

52500.0

In [ ]:
print(df[df['Department']=='It'])

    ID   Name Department  Salary
3  104  Kiran         It   55000

In [ ]:
 import pandas as pd
data = pd.read_excel("/content/employee.xlsx")
data

,Employee_ID,Name,Age,Gender,Department,Salary,City,Joining_Dates
0,E101,Akash,25.0,M,IT,45000,Bengaluru,2023-01-12
1,E102,Megha,NaN,F,HR,38000,Chennai,2022-02-15
2,E103,John,28.0,Male,Finance,55000,NaN,2023-05-10
3,NaN,Kavya,240.0,Female,IT,48000,Mysuru,2023-03-20
4,E105,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
5,E106,Supriya,NaN,Female,HR,-38000,Chennai,2022-02-15
6,E107,Darshi,26.0,Male,Sales,25000,Bengaluru,2021-06-10
7,E108,Sneha,23.0,NaN,IT,47000,Delhi,2023-02-01
8,E109,NaN,-27.0,Female,Finance,52000,Hyderabad,2022-08-22
9,E110,Vikas,22.0,Male,IT,99999,Chennai,2024-01-05